### ISSUE TITLE
Some nodes counted twice

### ISSUE THREAD

**Issue by okoverland** [zeux/pugixml#380] opened 2020-11-20 12:50 UTC
Our software uses pugixml 1.7 (we will update to more recent version in our next mayor release in Q4 2021) to parse xml files of building components and output results to Excel, so I don't know if this bug has already been fixed. We've encountered a problem where some nodes are counted twice. The nodes in question are parts inside a "beam panel".

Looking at a specific component "BE2", we know there are 5 of them. 
Using https://codebeautify.org/Xpath-Tester with attached XML file and expression: 
.//FRAMEPIECES/FRAMEPIECE/ATTRIBUTES[CODE[starts-with(text(),'IB-')] and COMP_ID[contains(text(),'BE2')]]
5 different nodes are collected, witch is correct.

For our 5 collected "beam panels", there should be in each 1 beam and 2 web plates, total of 5 and 10 respectively. 
Looking at our Excel output, there are however 9 beams and 18 web plates. We've found out that for 1 match of "BE2", child nodes are counted correct, but for following nodes, the children are doubled (5 -> 1x1 + 2x4 = 9 beams, 2x1 + 2x8 = 18 web plates).

I made a list of nodes showing attribute OID (object ID), and you can see that for all but the first node, double nodes are collected ("doubleOID.png").

Investigation shows that the fault is in pugixml:
PUGI__FN xpath_node_set xml_node::select_nodes(const xpath_query& query) const

I've attached "components.xml" used for testing the issue.

Path to nodes in question is that is collected twice:
./components/elements/floorelement/elements/strbeam_element/attributes
Child beam:
./components/elements/floorelement/elements/strbeam_element/framepieces/attributes
Child web plates:
./components/elements/floorelement/elements/strbeam_element/framepieces/structuralparts/stiffener/attributes

[pugixml_error.zip](https://github.com/zeux/pugixml/files/5573533/pugixml_error.zip)

**Comment by zeux** [comment] 2020-11-21 03:28
Sorry, maybe I'm missing something.

The XPath tester you linked returns 5 nodes as a result of the XPath query.

When using current pugixml, or pugixml 1.7 from git tag v1.7, and the following test program:

```
#include "pugixml.hpp"

int main()
{
	pugi::xml_document doc;
	doc.load_file("components.xml");
	pugi::xpath_node_set ns = doc.select_nodes(".//FRAMEPIECES/FRAMEPIECE/ATTRIBUTES[CODE[starts-with(text(),'IB-')] and COMP_ID[contains(text(),'BE2')]]");

	printf("ns size %d\n", int(ns.size()));
}
```

I get the output `ns size 5` for both current version and 1.7. So I'm not sure I understand what the issue is?

**Comment by zeux** [comment] 2020-11-21 03:49
To be extra sure I've edited the program to print parent attribute's OIDs:

```
#include "pugixml.hpp"

int main()
{
        pugi::xml_document doc;
        doc.load_file("components.xml");
        pugi::xpath_node_set ns = doc.select_nodes(".//FRAMEPIECES/FRAMEPIECE/ATTRIBUTES[CODE[starts-with(text(),'IB-')] and COMP_ID[contains(text(),'BE2')]]");

        printf("ns size %d\n", int(ns.size()));

        for (pugi::xpath_node node: ns)
        {
                printf("%s\n", node.node().path().c_str());
                printf("%s\n", node.node().parent().attribute("OID").value());
        }
}
```

And this is the output, with OIDs being seemingly unique:

```
/mnt/c/work/pugixml $ c++ xpathtest.cpp src/pugixml.cpp -I src && ./a.out
ns size 5
/COMPONENTS/ELEMENTS/FLOORELEMENT/ELEMENTS/STRBEAM_ELEMENT/FRAMEPIECES/FRAMEPIECE/ATTRIBUTES
16776
/COMPONENTS/ELEMENTS/FLOORELEMENT/ELEMENTS/STRBEAM_ELEMENT/FRAMEPIECES/FRAMEPIECE/ATTRIBUTES
16768
/COMPONENTS/ELEMENTS/FLOORELEMENT/ELEMENTS/STRBEAM_ELEMENT/FRAMEPIECES/FRAMEPIECE/ATTRIBUTES
16760
/COMPONENTS/ELEMENTS/FLOORELEMENT/ELEMENTS/STRBEAM_ELEMENT/FRAMEPIECES/FRAMEPIECE/ATTRIBUTES
16752
/COMPONENTS/ELEMENTS/FLOORELEMENT/ELEMENTS/STRBEAM_ELEMENT/FRAMEPIECES/FRAMEPIECE/ATTRIBUTES
16744
```

**Comment by okoverland** [comment] 2020-11-24 12:36
Our compilation has no comment on following:

#define PUGIXML_WCHAR_MODE

That might play a role here. We have debugged it and result xpath_node_set has too many nodes

**Comment by zeux** [comment] 2020-11-24 16:57
PUGIXML_WCHAR_MODE doesn't matter for the result of the execution of XPath query above. If xpath_node_set has more than 5 nodes on this example, I can see the following two options:

- pugixml source code has been changed, which could have introduced a bug
- the document in question wasn't loaded from the provided XML file; instead it was, for example, constructed on the fly and too many nodes were introduced.

If you *can* provide a way to reproduce this bug, I'll be happy to look into this, but again the sample above confirms the XPath query works as expected.

**Comment by zeux** [comment] 2020-12-07 20:41
I'm going to close this because based on the information provided, the bug isn't with pugixml. If you get additional information about this, e.g. in a form of a standalone example that reproduces the problem, feel free to supply it in this issue.

**Closed** 2020-12-07 20:41 UTC
Labels: invalid
