### ISSUE TITLE
Potential null pointer dereference in `append_node()` function

### ISSUE THREAD

**Issue by valeriyvan** [zeux/pugixml#315] opened 2019-12-03 10:09 UTC
Static analyser of Xcode (version 11.2.1) reports potential null pointer dereference in `append_node()` function:

<img width="1169" alt="Screenshot 2019-12-03 at 11 07 22" src="https://user-images.githubusercontent.com/1630974/70041354-4e9aee00-15bd-11ea-929e-9e96c3cfd0b7.png">

**Comment by zeux** [comment] 2019-12-04 05:59
This and #314 share the root cause (append_node here is getting called from `node_copy_tree` via `append_new_node`) so closing as duplicate.

**Closed by zeux** 2019-12-04 05:59 UTC
Labels: duplicate
