### ISSUE TITLE
Open two files simultaneuosly

### ISSUE THREAD

**Issue by AlvarVG** [zeux/pugixml#94] opened 2016-03-29 14:52 UTC
I explain my case. I have two different objects, each one loads a different xml file. My pseudocode its something like this.

> I open the file number 1. 
> I acces file 1 without errors.
> I open the file number 2.
> I acces file 2 without error.
> I acces file 1 (looking for an specific node), i make the call node.child(name), but i get the default node xml_node();

I dont know is this is an issue or is just not supported. Could you bring some support?
Thanks for this amazing library.

**Comment by zeux** [comment] 2016-03-29 15:10
Are you using two separate xml_document objects for this?

**Comment by AlvarVG** [comment] 2016-03-29 15:15
Yes. I hace two different classes, each one managing one xml_document, they are conpletely separste one from the other, i manage each class from the main.

**Comment by zeux** [comment] 2016-03-30 00:29
Ok. This should work fine - separate xml_document objects don't have any shared state so loading the second one should not affect the first one.

Can you share the code you're using, or parts of it? My gut feeling is that either there's some issue in the code, or I don't understand the use case completely.

**Comment by AlvarVG** [comment] 2016-03-30 14:23
I cannot share the code, sorry. 
But i can tell you what i exactly do.

[Some code here]
Class1 obj1(filename1); //Here i open a xml_document object.
obj1.getInt(parms);//Here i go to the xml_document i look for a child with doc.child()
                              //and from that child i get the value node.attibute()
Class2 obj2(filename2);//Here i create a new file overriding the last file, a new xml_document is open
[Some code here]
obj1.getInt(params);//And here when i call doc.child() or node.child() i go to pugixml code and instead of having back xml_node(i), i get xml_node() the default node.
[Some code here]

The two files are different, the two classes are different, and the purpose of both xml files are different too. 

I hope this can help you to guess what is happening.

**Comment by zeux** [comment] 2016-04-03 01:36
This code looks reasonable but it's not enough to understand where the problem may be. It's really hard to guess - it's very very likely that the problem is in application code since pugixml has been used plenty of times in the same fashion, documents *never* share *any* state.

Maybe the parameters that you pass to getInt change between the calls. Or maybe you are redefining memory allocation functions (via set_memory_management_functions) and your allocator has an issue that pugixml exposes. Or maybe Class2 somehow interferes with the state of Class1 - e.g. by reusing the xml_document object.

**Comment by zeux** [comment] 2016-05-06 05:53
Closing due to lack of information.

**Closed by zeux** 2016-05-06 05:53 UTC
