### ISSUE TITLE
Segmentation fault when compiled with upcoming version of LLVM 

### ISSUE THREAD

**Issue by lpugin** [zeux/pugixml#629] opened 2024-09-12 12:00 UTC
We have been tracking an issue when writing files, and it turned out to be a problem with pugixml when built with the upcoming version of LLVM clang and with the compiler optimisation set to `-O2` or -`O3`.

For the history of the bug tracking and the bisect on emscripten and on llvm, see [this](https://github.com/emscripten-core/emscripten/issues/22552) issue on the emcripten repository.

I narrowed it down to this example code:
```cpp
#include "pugixml.hpp"

int main() {
    
    pugi::xml_document doc;

    pugi::xml_parse_result result = doc.load_file("test-data.mei");
    
    doc.save_file("out.xml");

    return 0;
}
```
and the following [`test-data.mei`](https://gist.github.com/lpugin/e7a6c742b104c5db728bed125e056833#file-test-data-mei) file - even though the is nothing particular with the data and I am providing it only for testing consistency.

When built on macos with `Apple clang version 15.0.0 (clang-1500.3.9.4)`, there is no problem.

When built with `Homebrew clang version 20.0.0git (https://github.com/llvm/llvm-project.git 7294396a0878a6bd179fac9aa5c3743832c799f4)` and with
```
/opt/homebrew/opt/llvm/bin/clang++  main.cpp pugixml.cpp -o test -O2 
```
a segmentation fault occurs.

As pointed in the issue on the emscripten repository, it seems to be in `xml_buffered_writer::write_string`, but since this occurs only with `-O2` or `-O3` I do not have more precise information. The [last comment](https://github.com/emscripten-core/emscripten/issues/22552#issuecomment-2345089675) provided by @aheejin will hopefully be helpful.

Thanks for this great library!

**Comment by zeux** [comment] 2024-09-12 16:32
For completeness, how did you install homebrew clang 20? `brew install llvm` installs clang 18.

**Comment by lpugin** [comment] 2024-09-12 16:35
I did `brew install llvm --HEAD`

**Comment by zeux** [comment] 2024-09-12 16:48
Okay, going to try to reproduce and debug. This *really* seems like a miscompile to me, I don't think the code has overflows in any computations, and I think integer sanitizer was silent, but definitely possible LLVM is the first to hit this problem; this code has not changed in 10 years.

**Comment by sbc100** [comment] 2024-09-12 16:54
Yes, we should certainly bring this up in the LLVM commit that triggered this: https://github.com/llvm/llvm-project/pull/107257.   Seems like it could well be a compiler bug.

**Comment by zeux** [comment] 2024-09-12 17:01
The problem goes away when `get_valid_length` is marked as noinline (not super surprising). Adding this printf to `get_valid_length` preserves the crash, but allows to confirm that the string passed in is valid and addressable:

```
		printf("get_valid_length %p %d; %.*s\n", data, (int)length, (int)length, data);
```

The program crashes on the first invocation of `get_valid_length`.

Rewriting the code like this:

```
		const char_t* end = data + length;

		for (int i = 1; i <= 4; ++i)
		{
			uint8_t ch = static_cast<uint8_t>(end[-i]);
```

"fixes" the problem. This should be equivalent to the original code:

```
		for (size_t i = 1; i <= 4; ++i)
		{
			uint8_t ch = static_cast<uint8_t>(data[length - i]);
```

... assuming that `length - i` doesn't underflow (which it doesn't because `length` must be at least 5 per early return in the function).

Will try to debug this further to reduce an example; it is still possible there is some problem in the call to `get_valid_length` that is not the compiler's fault.

**Comment by zeux** [comment] 2024-09-12 17:07
Err, the crash is due to the compiler generating a load from a constant `-1` pointer? :)

```
    0x55555556126b <+187>: call   0x555555556030 ; symbol stub for: printf
->  0x555555561270 <+192>: movzx  eax, byte ptr [-0x1]
```

(the call to printf is per the modification above).

**Comment by zeux** [comment] 2024-09-12 17:18
I've extracted this example to make the repro case not depend on pugixml.

```
#include <stdio.h>
#include <stdint.h>
#include <string.h>

size_t get_valid_length(const char* data, size_t length)
{
	if (length < 5) return 0;

	printf("get_valid_length %p %d; %.*s\n", data, (int)length, (int)length, data);

	for (size_t i = 1; i <= 4; ++i)
	{
		uint8_t ch = static_cast<uint8_t>(data[length - i]);

		// either a standalone character or a leading one
		if ((ch & 0xc0) != 0x80) return length - i;
	}

	// there are four non-leading characters at the end, sequence tail is broken so might as well process the whole chunk
	return length;
}

class xml_buffered_writer
{
public:
	xml_buffered_writer(): bufsize(0)
	{
	}

	__attribute__((noinline))
	void write_string(const char* data)
	{
		// write the part of the string that fits in the buffer
		size_t offset = bufsize;

		while (*data && offset < bufcapacity)
			buffer[offset++] = *data++;

		// write the rest
		if (offset < bufcapacity)
		{
			bufsize = offset;
		}
		else
		{
			// backtrack a bit if we have split the codepoint
			size_t length = offset - bufsize;
			size_t extra = length - get_valid_length(data - length, length);

			bufsize = offset - extra;
		}
	}

	enum
	{
		bufcapacity = 16
	};

	char buffer[bufcapacity];
	size_t bufsize;
};

int main()
{
	xml_buffered_writer writer;
	writer.write_string("abcdefghijklmnopqrstuvwxyz");
	printf("\n");
}
```

**Comment by zeux** [comment] 2024-09-12 17:48
I've linked the reproducer above, as well as a slightly smaller one, in the LLVM issue. https://github.com/llvm/llvm-project/pull/107257#issuecomment-2346895150

I am assuming LLVM commit gets reverted. If that doesn't happen for some reason I can commit a workaround to pugixml codebase, but I'll wait for a decision to be made on LLVM side.

**Comment by zeux** [comment] 2024-09-13 15:48
This issue has been fixed by https://github.com/llvm/llvm-project/commit/940f89255e4a3982d94dad57837e8e658092af78.

**Closed as not planned** 2024-09-13 15:48 UTC
Labels: bug, invalid
