### ISSUE TITLE
Getting the line of parse error instead of char offset would help a lot for error messages

### ISSUE THREAD

**Issue by olowo726** [zeux/pugixml#531] opened 2022-11-11 05:45 UTC
Hi,

I think it would be great if one could get the line and row of a parse error instead of only a character offset. Can that be done?

**Comment by zeux** [comment] 2022-11-11 20:37
Duplicate of #12. This requires a separate tracking structure that isn't free.

**Closed by zeux** 2022-11-11 20:37 UTC
Labels: enhancement
