### ISSUE TITLE
Should explicitly support `xml:space="preserve"`

### ISSUE THREAD

**Issue by TPS** [zeux/pugixml#74] opened 2015-12-28 17:36 UTC
Details as to necessity at https://github.com/leethomason/tinyxml2/issues/242, & https://github.com/JayXon/Leanify/issues/3#issuecomment-167585082 & preceding.

**Comment by zeux** [comment] 2016-01-10 02:08
So it seems that the cost of this feature outweighs the benefits.

The linked issue in Leanify would be resolved by both xml:space=preserve support, or by using parse_ws_pcdata_single (or parse_ws_pcdata and some advanced client code that strips unused whitespace - parse_ws_pcdata_single is inadequate for e.g. XHTML parsing).

Interestingly enough, the issue in tinyxml2 does *not* have xml:space="preserve" in the document, so it's irrelevant there - this is already served by parse_ws_* parsing flags pugixml provides. In general, for XHTML documents xml:space="preserve" won't help because it's almost never present in the documents directly.

Now, there's still *some* value in automatic preservation of whitespace if needed. XML recommendation seems to suggest that support for this is preferred. The problem is that implementation is very involved:

- Requires tracking this flag during parsing for the entire subtree. Since pugixml uses a stackless parser, it's not obvious how to cleanly implement this without additional storage *and* without the need to examine the presence of the attribute whenever you close the node
- Requires analyzing the attribute names during parsing which adds overhead to one of the hottest paths in the parser for some documents
- *or* requires inspecting the attribute state during PCDATA parsing, which is once again one of the hottest paths in the parser

Combining the implementation challenges with the fact that in most cases the applications don't seem to benefit from this means that supporting this is not worth the trouble.

**Closed by zeux** 2016-01-10 02:08 UTC
Labels: enhancement

**Comment by TPS** [comment] 2016-01-10 04:43
Thanks for investigating this!
